ci(github): use GitHub public artifact API when downloading artifacts from CircleCI
Signed-off-by: Jay Chen <1180092+jijiechen@users.noreply.github.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,10 +16,7 @@ parameters:
   gh_action_build_artifact_name:
     type: string
     default: ""
-  gh_action_artifact_list_url:
-    type: string
-    default: ""
-  gh_action_runtime_token:
+  gh_action_run_id:
     type: string
     default: ""
   e2e_param_k8sVersion:
@@ -415,6 +412,7 @@ jobs:
       - run:
           name: Download build output from GitHub action
           command: |
+            set -e
             echo "Running with: \
               k8s:<< parameters.k8sVersion >> \
               target:<< parameters.target >> \
@@ -423,42 +421,40 @@ jobs:
               legacyKDS:<< parameters.legacyKDS >> \
               cniNetworkPlugin:<< parameters.cniNetworkPlugin >> \
             "
-            set +x
-
-            GH_ARTIFACT_LIST_URL=<< pipeline.parameters.gh_action_artifact_list_url >>
-            GH_ACTIONS_RUNTIME_TOKEN=<< pipeline.parameters.gh_action_runtime_token >>
-            GH_ACTIONS_BUILD_ARTIFACT_NAME=<< pipeline.parameters.gh_action_build_artifact_name >>
-            BASE_DIR=build
-
-            if [[ "$GH_ACTIONS_RUNTIME_TOKEN" == "" ]]; then
-                echo "Please set these environment variables: GH_ACTIONS_RUNTIME_TOKEN"
+            if [[ "${GITHUB_TOKEN}" == "" ]]; then
+                echo "Please set value for environment variables: GITHUB_TOKEN"
                 exit 1
             fi
+
+            GH_ACTIONS_RUN_ID=<< pipeline.parameters.gh_action_run_id >>
+            GH_ACTIONS_BUILD_ARTIFACT_NAME=<< pipeline.parameters.gh_action_build_artifact_name >>
+            ARCH='<< parameters.arch >>'
+            BASE_DIR=build
 
             if [[ "$BASE_DIR" == "" ]]; then
                 BASE_DIR="."
             fi
 
             function request(){
-                METHOD=$1
-                URL=$2
-                IS_STREAM=$3
+                URL=$1
+                IS_STREAM=$2
 
                 if [[ "$URL" == "" ]]; then
-                    echo "Unknown URL"
-                    exit 1
+                    echo "Error: unknown URL"
+            	    return
                 fi
 
-                ACCEPT=application/json
+                ACCEPT=application/vnd.github+json
                 if [[ "$IS_STREAM" == "1" ]]; then
                     ACCEPT="*/*"
                 fi
 
                 OUTPUT_FILE=/tmp/gh-response-$RANDOM
+                touch $OUTPUT_FILE
                 STATUS_CODE=
                 while [[ "$STATUS_CODE" == "" ]]; do
-                    STATUS_CODE=$(curl --compressed -o $OUTPUT_FILE -sL -w "%{http_code}" -X $METHOD $URL \
-                    --header "accept: $ACCEPT" --header "Authorization: Bearer $GH_ACTIONS_RUNTIME_TOKEN")
+                    STATUS_CODE=$(curl --compressed -o $OUTPUT_FILE -sL -w "%{http_code}" $URL \
+                    --header "accept: $ACCEPT" --header "Authorization: Bearer ${GITHUB_TOKEN}" --header "X-GitHub-Api-Version: 2022-11-28")
 
                     if [[ "$STATUS_CODE" == "429" ]]; then
                         STATUS_CODE=
@@ -468,49 +464,56 @@ jobs:
                 done
 
                 if [ $STATUS_CODE -lt 200 ] || [ $STATUS_CODE -gt 399 ] ; then
-                    echo "Error requesting $METHOD $URL (status $STATUS_CODE)"
-                    exit 1
+                    echo "Error requesting $URL (status $STATUS_CODE)"
+                    return
                 fi
                 if [[ "$IS_STREAM" != "1" ]]; then
-                    cat $OUTPUT_FILE
+                    cat $OUTPUT_FILE | tr '\n' ' ' | jq -Rc "fromjson | ."
                     rm $OUTPUT_FILE
                 else
                     echo "$OUTPUT_FILE"
                 fi
             }
+
             echo "Listing artifacts..."
-            LIST_RESP=$(request GET "$GH_ARTIFACT_LIST_URL")
+            GITHUB_PROJECT="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
+            LIST_RESP=$(request "https://api.github.com/repos/$GITHUB_PROJECT/actions/runs/$GH_ACTIONS_RUN_ID/artifacts")
             if [[ "${LIST_RESP:0:5}" == "Error" ]]; then
               echo "List response seems to be an error"
               echo "$LIST_RESP"
               exit 1
             fi
-            FILE_LIST_URL=$(echo "$LIST_RESP" | jq -rc '.value[0].fileContainerResourceUrl //empty')
-            LIST_JSON_FILE=$(request GET "$FILE_LIST_URL" 1)
-            while read FILE_PATH; do
-              DOWNLOAD_URL=$(cat $LIST_JSON_FILE | jq -rc ".value[] | select(.path==\"$FILE_PATH\") | .contentLocation")
-              FILE_SIZE=$(cat $LIST_JSON_FILE | jq -rc ".value[] | select(.path==\"$FILE_PATH\") | .fileLength")
 
-              FILE_PATH=${FILE_PATH#*/}
-              echo "Downloading $FILE_PATH (size: $FILE_SIZE)"
-              mkdir -p $(dirname $BASE_DIR/$FILE_PATH)
-              FILE_SAVED=$(request GET "$DOWNLOAD_URL" 1)
-              mv $FILE_SAVED $BASE_DIR/$FILE_PATH
-            done < <(cat $LIST_JSON_FILE | jq -rc ".value[] | select((.itemType==\"file\") and (.path|startswith(\"$GH_ACTIONS_BUILD_ARTIFACT_NAME/\"))) | .path")
+            TARGET_ARTIFACT=$(echo "$LIST_RESP" | tr '\n' ' ' | jq -Rrc "fromjson | .artifacts[] | select(.name==\"$GH_ACTIONS_BUILD_ARTIFACT_NAME\") //empty")
+            if [[ "$TARGET_ARTIFACT" == "" ]]; then
+              echo "Could not find artifact $GH_ACTIONS_BUILD_ARTIFACT_NAME in run $GH_ACTIONS_RUN_ID."
+              exit 1
+            fi
+            if [[ "$(echo $TARGET_ARTIFACT | jq -rc '.expired')" == "true" ]]; then
+              echo "Artifact $GH_ACTIONS_BUILD_ARTIFACT_NAME in run $GH_ACTIONS_RUN_ID has expired."
+              exit 1
+            fi
 
+            DOWNLOAD_URL=$(echo $TARGET_ARTIFACT | jq -rc ".archive_download_url")
+            FILE_SIZE=$(echo $TARGET_ARTIFACT | jq -rc ".size_in_bytes")
+
+            echo "Downloading... (size: $FILE_SIZE)"
+            FILE_SAVED=$(request "$DOWNLOAD_URL" 1)
+            mv $FILE_SAVED ${FILE_SAVED}.zip
             echo "Downloading complete."
 
             echo "Extracting files..."
-            ARCH='<< parameters.arch >>'
-            ARTIFACT=$(find $BASE_DIR/distributions/out/*-linux-$ARCH.tar.gz)
-            if [[ "$ARTIFACT" == "" ]]; then
+            unzip ${FILE_SAVED}.zip -d $BASE_DIR
+
+            TARBALL=$(find $BASE_DIR/distributions/out/*-linux-$ARCH.tar.gz)
+            if [[ "$TARBALL" == "" ]]; then
               echo "Could not find built artifact for linux($ARCH)."
               exit 1
             fi
-            cat $ARTIFACT.sha256 | sha256sum --check
+            cat ${TARBALL}.sha256 | sha256sum --check
 
             mkdir $BASE_DIR/distributions/artifacts
-            tar -xzf $ARTIFACT -C $BASE_DIR/distributions/artifacts
+            tar -xzf $TARBALL -C $BASE_DIR/distributions/artifacts
 
             SRC_DIR=$(find build/distributions/artifacts/*/bin -type d)
             DEST_DIR=$BASE_DIR/artifacts-linux-$ARCH
