ci(check): fail CI wih `ci/force-publish` label on PRs from forks (backport of #9801) (#9805)
* ci(check): fail CI wih `ci/force-publish` label on PRs from forks (#9801)

There is no access to secrets on a PRs from forks, so to have
a quick feedback, whole workflow will immediately fail when
CI will detect `ci/force-publish` label on such PRs.

Signed-off-by: Bart Smykla <bartek@smykla.com>

diff --git a/.github/workflows/build-test-distribute.yaml b/.github/workflows/build-test-distribute.yaml
--- a/.github/workflows/build-test-distribute.yaml
+++ b/.github/workflows/build-test-distribute.yaml
@@ -24,6 +24,11 @@ jobs:
     timeout-minutes: 15
     runs-on: ubuntu-latest
     steps:
+      - name: "Fail when 'ci/force-publish' label is present on PRs from forks"
+        if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/force-publish') && github.event.pull_request.head.repo.full_name != github.repository }}
+        run: |
+          echo "::error title=Label 'ci/force-publish' cannot be used on PRs from forks::To prevent accidental exposure of secrets, CI won't use repository secrets on pull requests from forks"
+          exit 1
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
         with:
           fetch-depth: 0
